spring:
  datasource:
    url: jdbc:mysql://106.14.0.99:3308/jobmanager?useUnicode=true&serverTimezone=GMT&autoReconnect=true&useSSL=false
    username: root
    password: mysqlqwedc3
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      test-on-borrow: true
      test-while-idle: true
      validationQuery: true
mybatis: 
  mapper-locations:
  - classpath:com/tongsh6/quartz/JobManager/mapper/*.xml
  type-aliases-package: com.tongsh6.exercise.JobManager.entity
    